In [21]:
# Import pandas
import pandas as pd

# Load dataset
cc_apps = pd.read_csv("datasets/Predicting Credit Card Approvals/cc_approvals.TXT",header= None)

# Inspect data
cc_apps

    0      1       2  3  4   5   6     7  8  9   10 11 12     13   14 15
0    b  30.83   0.000  u  g   w   v  1.25  t  t   1  f  g  00202    0  +
1    a  58.67   4.460  u  g   q   h  3.04  t  t   6  f  g  00043  560  +
2    a  24.50   0.500  u  g   q   h  1.50  t  f   0  f  g  00280  824  +
3    b  27.83   1.540  u  g   w   v  3.75  t  t   5  t  g  00100    3  +
4    b  20.17   5.625  u  g   w   v  1.71  t  f   0  f  s  00120    0  +
..  ..    ...     ... .. ..  ..  ..   ... .. ..  .. .. ..    ...  ... ..
685  b  21.08  10.085  y  p   e   h  1.25  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.00  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.00  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.04  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.29  f  f   0  t  g  00000    0  -

[690 rows x 16 columns]

## 2. Inspecting the applications
The output may appear a bit confusing at its first sight, but let's try to figure out the most important features of a credit card application. The features of this dataset have been anonymized to protect the privacy, but this blog gives us a pretty good overview of the probable features. The probable features in a typical credit card application are Gender, Age, Debt, Married, BankCustomer, EducationLevel, Ethnicity, YearsEmployed, PriorDefault, Employed, CreditScore, DriversLicense, Citizen, ZipCode, Income and finally the ApprovalStatus. This gives us a pretty good starting point, and we can map these features with respect to the columns in the output.

As we can see from our first glance at the data, the dataset has a mixture of numerical and non-numerical features. This can be fixed with some preprocessing, but before we do that, let's learn about the dataset a bit more to see if there are other dataset issues that need to be fixed.

In [22]:
# Print summary statistics
cc_apps_description = cc_apps.describe()
print(cc_apps_description)

print('\n')

# Print DataFrame information
cc_apps_info = cc_apps.info()
print(cc_apps_info)

print('\n')

# Inspect missing values in the dataset

               2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       690 non-null    object
 1   1       690 non-null    object
 2   2       690 non-null    float64
 3   3       690 non-null    object
 4   4       690 non-null    object
 5   5       690 non-null    object
 6   6       690 non-null    object
 7   7       690 non-null    float64
 8   8       690 non-null    object
 9   9       690 non-null    object
 10  10      690 non-null    int64
 11  11      690 non-null    object
 12  12      690 non-null    object
 13  13      690 non-null    object
 14  14      690 non-null    int64
 15  15      690 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB
None

## 3. Splitting the dataset into train and test sets
Now, we will split our data into train set and test set to prepare our data for two different phases of machine learning modeling: training and testing. Ideally, no information from the test data should be used to preprocess the training data or should be used to direct the training process of a machine learning model. Hence, we first split the data and then preprocess it.

Also, features like DriversLicense and ZipCode are not as important as the other features in the dataset for predicting credit card approvals. To get a better sense, we can measure their statistical correlation to the labels of the dataset. But this is out of scope for this project. We should drop them to design our machine learning model with the best set of features. In Data Science literature, this is often referred to as feature selection.

In [23]:
# Import train_test_split
from sklearn.model_selection import train_test_split

# Drop the features 11 and 13
cc_apps = cc_apps.drop(cc_apps.columns[[11, 13]], axis = 1)

# Split into train and test sets
cc_apps_train, cc_apps_test = train_test_split(cc_apps, test_size=0.33, random_state=42)
cc_apps

    0      1       2  3  4   5   6     7  8  9   10 12   14 15
0    b  30.83   0.000  u  g   w   v  1.25  t  t   1  g    0  +
1    a  58.67   4.460  u  g   q   h  3.04  t  t   6  g  560  +
2    a  24.50   0.500  u  g   q   h  1.50  t  f   0  g  824  +
3    b  27.83   1.540  u  g   w   v  3.75  t  t   5  g    3  +
4    b  20.17   5.625  u  g   w   v  1.71  t  f   0  s    0  +
..  ..    ...     ... .. ..  ..  ..   ... .. ..  .. ..  ... ..
685  b  21.08  10.085  y  p   e   h  1.25  f  f   0  g    0  -
686  a  22.67   0.750  u  g   c   v  2.00  f  t   2  g  394  -
687  a  25.25  13.500  y  p  ff  ff  2.00  f  t   1  g    1  -
688  b  17.92   0.205  u  g  aa   v  0.04  f  f   0  g  750  -
689  b  35.00   3.375  u  g   c   h  8.29  f  f   0  g    0  -

[690 rows x 14 columns]

## 4. Handling the missing values (part i)
Now we've split our data, we can handle some of the issues we identified when inspecting the DataFrame, including:

Our dataset contains both numeric and non-numeric data (specifically data that are of float64, int64 and object types). Specifically, the features 2, 7, 10 and 14 contain numeric values (of types float64, float64, int64 and int64 respectively) and all the other features contain non-numeric values.
The dataset also contains values from several ranges. Some features have a value range of 0 - 28, some have a range of 2 - 67, and some have a range of 1017 - 100000. Apart from these, we can get useful statistical information (like mean, max, and min) about the features that have numerical values.
Finally, the dataset has missing values, which we'll take care of in this task. The missing values in the dataset are labeled with '?', which can be seen in the last cell's output of the second task.
Now, let's temporarily replace these missing value question marks with NaN.

In [24]:
# Import numpy
import numpy as np

# Replace the '?'s with NaN in the train and test sets
cc_apps_train = cc_apps_train.replace("?","NaN")
cc_apps_test = cc_apps_test.replace("?","NaN")
print(cc_apps_train, "\n\n")
print(cc_apps_train.iloc[:,[2,7,10,12]])

      0      1      2    3    4    5    6       7  8  9   10 12    14 15
382    a  24.33  2.500    y    p    i   bb   4.500  f  f   0  g   456  -
137    b  33.58  2.750    u    g    m    v   4.250  t  t   6  g     0  +
346  NaN  32.25  1.500    u    g    c    v   0.250  f  f   0  g   122  -
326    b  30.17  1.085    y    p    c    v   0.040  f  f   0  g   179  -
33     a  36.75  5.125    u    g    e    v   5.000  t  f   0  g  4000  +
..   ...    ...    ...  ...  ...  ...  ...     ... .. ..  .. ..   ... ..
71     b  34.83  4.000    u    g    d   bb  12.500  t  f   0  g     0  -
106    b  28.75  1.165    u    g    k    v   0.500  t  f   0  s     0  -
270    b  37.58  0.000  NaN  NaN  NaN  NaN   0.000  f  f   0  p     0  +
435    b  19.00  0.000    y    p   ff   ff   0.000  f  t   4  g     1  -
102    b  18.67  5.000    u    g    q    v   0.375  t  t   2  g    38  -

[462 rows x 14 columns]


        2       7   10    14
382  2.500   4.500   0   456
137  2.750   4.250   6     0
346  1.500   0.250   0   122
326  1.085   0.040   0   179
33   5.125   5.000   0  4000
..     ...     ...  ..   ...
71   4.000  12.500   0     0
106  1.165   0.500   0     0
270  0.000   0.000   0     0
435  0.000   0.000   4     1
102  5.000   0.375   2    38

[462 rows x 4 columns]

## 5. Handling the missing values (part ii)
We replaced all the question marks with NaNs. This is going to help us in the next missing value treatment that we are going to perform.

An important question that gets raised here is why are we giving so much importance to missing values? Can't they be just ignored? Ignoring missing values can affect the performance of a machine learning model heavily. While ignoring the missing values our machine learning model may miss out on information about the dataset that may be useful for its training. Then, there are many models which cannot handle missing values implicitly such as Linear Discriminant Analysis (LDA).

So, to avoid this problem, we are going to impute the missing values with a strategy called mean imputation.

In [25]:
# Impute the missing values with mean imputation
cc_apps_train.iloc[:,[2,7,10,12]].fillna(cc_apps_train.iloc[:,[2,7,10,12]].mean(), inplace=True)
cc_apps_test.iloc[:,[2,7,10,12]].fillna(cc_apps_train.iloc[:,[2,7,10,12]].mean(), inplace=True)

# Count the number of NaNs in the datasets and print the counts to verify
print(cc_apps_train.isna().sum())
print(cc_apps_test.isna().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
12    0
14    0
15    0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
12    0
14    0
15    0
dtype: int64

C:\Users\hp\anaconda3\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

## 6. Handling the missing values (part iii)
We have successfully taken care of the missing values present in the numeric columns. There are still some missing values to be imputed for columns 0, 1, 3, 4, 5, 6 and 13. All of these columns contain non-numeric data and this is why the mean imputation strategy would not work here. This needs a different treatment.

We are going to impute these missing values with the most frequent values as present in the respective columns. This is good practice when it comes to imputing missing values for categorical data in general.

In [26]:
# Iterate over each column of cc_apps_train
for col in cc_apps_train.columns:
    # Check if the column is of object type
    if col == 'object':
        # Impute with the most frequent value
        cc_apps_train = cc_apps_train.fillna(cc_apps_train.value_counts())
        cc_apps_test = cc_apps_test.fillna(cc_apps_test.value_counts())

# Count the number of NaNs in the dataset and print the counts to verify
print(cc_apps_train.isna().sum(), "\n\n")
print(cc_apps_test.isna().sum(), "\n\n")
print(cc_apps_train)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
12    0
14    0
15    0
dtype: int64


0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
12    0
14    0
15    0
dtype: int64


      0      1      2    3    4    5    6       7  8  9   10 12    14 15
382    a  24.33  2.500    y    p    i   bb   4.500  f  f   0  g   456  -
137    b  33.58  2.750    u    g    m    v   4.250  t  t   6  g     0  +
346  NaN  32.25  1.500    u    g    c    v   0.250  f  f   0  g   122  -
326    b  30.17  1.085    y    p    c    v   0.040  f  f   0  g   179  -
33     a  36.75  5.125    u    g    e    v   5.000  t  f   0  g  4000  +
..   ...    ...    ...  ...  ...  ...  ...     ... .. ..  .. ..   ... ..
71     b  34.83  4.000    u    g    d   bb  12.500  t  f   0  g     0  -
106    b  28.75  1.165    u    g    k    v   0.500  t  f   0  s     0  -
270    b  37.58  0.000  NaN  NaN  NaN  NaN   0.000  f  f   0  p     0  +
435    b  19.00  0.000    y    p   ff   ff   0.000  f  t   4  g     1  -
102    b  18.67  5.000    u    g    q    v   0.375  t  t   2  g    38  -

[462 rows x 14 columns]

## 7. Preprocessing the data (part i)
The missing values are now successfully handled.

There is still some minor but essential data preprocessing needed before we proceed towards building our machine learning model. We are going to divide these remaining preprocessing steps into two main tasks:

Convert the non-numeric data into numeric.
Scale the feature values to a uniform range.
First, we will be converting all the non-numeric values into numeric ones. We do this because not only it results in a faster computation but also many machine learning models (like XGBoost) (and especially the ones developed using scikit-learn) require the data to be in a strictly numeric format. We will do this by using the get_dummies() method from pandas.

In [27]:
# Convert the categorical features in the train and test sets independently
cc_apps_train = pd.get_dummies(cc_apps_train)
cc_apps_test = pd.get_dummies(cc_apps_test)

# Reindex the columns of the test set aligning with the train set
cc_apps_test = cc_apps_test.reindex(columns=cc_apps_train.columns, fill_value=0)

print(cc_apps_train,"\n\n")
print(cc_apps_test,"\n\n")

         2       7  10    14  0_NaN  0_a  0_b  1_13.75  1_15.83  1_15.92  ...  \
382  2.500   4.500   0   456      0    1    0        0        0        0  ...
137  2.750   4.250   6     0      0    0    1        0        0        0  ...
346  1.500   0.250   0   122      1    0    0        0        0        0  ...
326  1.085   0.040   0   179      0    0    1        0        0        0  ...
33   5.125   5.000   0  4000      0    1    0        0        0        0  ...
..     ...     ...  ..   ...    ...  ...  ...      ...      ...      ...  ...
71   4.000  12.500   0     0      0    0    1        0        0        0  ...
106  1.165   0.500   0     0      0    0    1        0        0        0  ...
270  0.000   0.000   0     0      0    0    1        0        0        0  ...
435  0.000   0.000   4     1      0    0    1        0        0        0  ...
102  5.000   0.375   2    38      0    0    1        0        0        0  ...

     6_z  8_f  8_t  9_f  9_t  12_g  12_p  12_s  15_+  15_-
382    0    1    0    1    0     1     0     0     0     1
137    0    0    1    0    1     1     0     0     1     0
346    0    1    0    1    0     1     0     0     0     1
326    0    1    0    1    0     1     0     0     0     1
33     0    0    1    1    0     1     0     0     1     0
..   ...  ...  ...  ...  ...   ...   ...   ...   ...   ...
71     0    0    1    1    0     1     0     0     0     1
106    0    0    1    1    0     0     0     1     0     1
270    0    1    0    1    0     0     1     0     1     0
435    0    1    0    0    1     1     0     0     0     1
102    0    0    1    0    1     1     0     0     0     1

[462 rows x 335 columns]


         2       7  10    14  0_NaN  0_a  0_b  1_13.75  1_15.83  1_15.92  ...  \
286   1.50   0.000   2   105      0    1    0        0        0        0  ...
511   4.00   0.000   0   960      0    1    0        0        0        0  ...
257   0.00   0.500   0     0      0    0    1        0        0        0  ...
336   6.50   1.000   0   228      0    0    1        0        0        0  ...
318   0.00   0.000   0     1      0    0    1        0        0        0  ...
..     ...     ...  ..   ...    ...  ...  ...      ...      ...      ...  ...
375   0.50   1.000   0     0      0    1    0        0        0        0  ...
234  21.00  10.000  13  6700      0    1    0        0        0        0  ...
644   0.42   0.290   0     2      0    0    1        0        0        0  ...
271   2.50   1.250   0     0      0    0    1        0        0        0  ...
311   1.75   2.335   0     6      0    0    1        0        0        0  ...

     6_z  8_f  8_t  9_f  9_t  12_g  12_p  12_s  15_+  15_-
286    0    1    0    0    1     1     0     0     0     1
511    0    0    1    1    0     1     0     0     1     0
257    0    1    0    1    0     1     0     0     0     1
336    0    1    0    1    0     1     0     0     0     1
318    0    1    0    1    0     0     0     1     1     0
..   ...  ...  ...  ...  ...   ...   ...   ...   ...   ...
375    0    1    0    1    0     1     0     0     0     1
234    0    0    1    0    1     1     0     0     1     0
644    0    1    0    1    0     1     0     0     0     1
271    0    1    0    1    0     1     0     0     0     1
311    0    1    0    1    0     1     0     0     0     1

[228 rows x 335 columns]

## 8. Preprocessing the data (part ii)
Now, we are only left with one final preprocessing step of scaling before we can fit a machine learning model to the data.

Now, let's try to understand what these scaled values mean in the real world. Let's use CreditScore as an example. The credit score of a person is their creditworthiness based on their credit history. The higher this number, the more financially trustworthy a person is considered to be. So, a CreditScore of 1 is the highest since we're rescaling all the values to the range of 0-1.

In [44]:
# Import MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

# Segregate features and labels into separate variables
X_train, y_train = cc_apps_train.iloc[:,0:-1].values, cc_apps_train.iloc[:,-1].values
X_test, y_test = cc_apps_test.iloc[:,0:-1].values, cc_apps_test.iloc[:,-1].values

# Instantiate MinMaxScaler and use it to rescale X_train and X_test
scaler = MinMaxScaler(feature_range = (0,1))
rescaledX_train = scaler.fit_transform(X_train)
rescaledX_test = scaler.transform(X_test)

print(rescaledX_train,"\n\n")
print(rescaledX_test,"\n\n")

print(len(rescaledX_train) == len(y_train))
print(len(rescaledX_train))
print(len(y_train))

[[0.0949307  0.225      0.         ... 0.         0.         0.        ]
 [0.10442377 0.2125     0.08955224 ... 0.         0.         1.        ]
 [0.05695842 0.0125     0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         1.        ]
 [0.         0.         0.05970149 ... 0.         0.         0.        ]
 [0.1898614  0.01875    0.02985075 ... 0.         0.         0.        ]]


[[0.05695842 0.         0.02985075 ... 0.         0.         0.        ]
 [0.15188912 0.         0.         ... 0.         0.         1.        ]
 [0.         0.025      0.         ... 0.         0.         0.        ]
 ...
 [0.01594836 0.0145     0.         ... 0.         0.         0.        ]
 [0.0949307  0.0625     0.         ... 0.         0.         0.        ]
 [0.06645149 0.11675    0.         ... 0.         0.         0.        ]]


True
462
462

## 9. Fitting a logistic regression model to the train set
Essentially, predicting if a credit card application will be approved or not is a classification task. According to UCI, our dataset contains more instances that correspond to "Denied" status than instances corresponding to "Approved" status. Specifically, out of 690 instances, there are 383 (55.5%) applications that got denied and 307 (44.5%) applications that got approved.

This gives us a benchmark. A good machine learning model should be able to accurately predict the status of the applications with respect to these statistics.

Which model should we pick? A question to ask is: are the features that affect the credit card approval decision process correlated with each other? Although we can measure correlation, that is outside the scope of this notebook, so we'll rely on our intuition that they indeed are correlated for now. Because of this correlation, we'll take advantage of the fact that generalized linear models perform well in these cases. Let's start our machine learning modeling with a Logistic Regression model (a generalized linear model).

In [42]:
# Import LogisticRegression
from sklearn.linear_model import LogisticRegression 

# Instantiate a LogisticRegression classifier with default parameter values
logreg = LogisticRegression()

# Fit logreg to the train set
logreg.fit(rescaledX_train, y_train)

LogisticRegression()

## 10. Making predictions and evaluating performance
But how well does our model perform?

We will now evaluate our model on the test set with respect to classification accuracy. But we will also take a look the model's confusion matrix. In the case of predicting credit card applications, it is important to see if our machine learning model is equally capable of predicting approved and denied status, in line with the frequency of these labels in our original dataset. If our model is not performing well in this aspect, then it might end up approving the application that should have been approved. The confusion matrix helps us to view our model's performance from these aspects.

In [45]:
# Import confusion_matrix
from sklearn.metrics import confusion_matrix

# Use logreg to predict instances from the test set and store it
y_pred = logreg.predict(rescaledX_test)

# Get the accuracy score of logreg model and print it
print("Accuracy of logistic regression classifier: ", logreg.score(rescaledX_test, y_test))

# Print the confusion matrix of the logreg model
print(confusion_matrix(y_test,y_pred))

Accuracy of logistic regression classifier:  1.0
[[103   0]
 [  0 125]]

## 11. Grid searching and making the model perform better
Our model was pretty good! In fact it was able to yield an accuracy score of 100%.

For the confusion matrix, the first element of the of the first row of the confusion matrix denotes the true negatives meaning the number of negative instances (denied applications) predicted by the model correctly. And the last element of the second row of the confusion matrix denotes the true positives meaning the number of positive instances (approved applications) predicted by the model correctly.

But if we hadn't got a perfect score what's to be done?. We can perform a grid search of the model parameters to improve the model's ability to predict credit card approvals.

scikit-learn's implementation of logistic regression consists of different hyperparameters but we will grid search over the following two:

tol
max_iter

In [46]:
# Import GridSearchCV
from sklearn.model_selection import GridSearchCV

# Define the grid of values for tol and max_iter
tol = [0.01, 0.001, 0.0001]
max_iter = [100, 150, 200]

# Create a dictionary where tol and max_iter are keys and the lists of their values are corresponding values
param_grid = dict(tol = tol, max_iter = max_iter)

## 12. Finding the best performing model
We have defined the grid of hyperparameter values and converted them into a single dictionary format which GridSearchCV() expects as one of its parameters. Now, we will begin the grid search to see which values perform best.

We will instantiate GridSearchCV() with our earlier logreg model with all the data we have. We will also instruct GridSearchCV() to perform a cross-validation of five folds.

We'll end the notebook by storing the best-achieved score and the respective best parameters.

While building this credit card predictor, we tackled some of the most widely-known preprocessing steps such as scaling, label encoding, and missing value imputation. We finished with some machine learning to predict if a person's application for a credit card would get approved or not given some information about that person.

In [47]:
# Instantiate GridSearchCV with the required parameters
grid_model = GridSearchCV(estimator=logreg, param_grid=param_grid, cv=5)

# Fit grid_model to the data
grid_model_result = grid_model.fit(rescaledX_train, y_train)

# Summarize results
best_score, best_params = grid_model_result.best_score_, grid_model_result.best_params_
print("Best: %f using %s" % (best_score, best_params))

# Extract the best model and evaluate it on the test set
best_model = grid_model_result.best_estimator_
print("Accuracy of logistic regression classifier: " ,best_model.score(rescaledX_test,y_test))

Best: 1.000000 using {'max_iter': 100, 'tol': 0.01}
Accuracy of logistic regression classifier:  1.0